stages:
  - deploy_dev_job

deploy_dev_job:
  stage: deploy_dev_job
  tags:
    - frontend
  only:
    - develop
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[ci.skip\]/
  environment:
    name: dev
  before_script:
    - mkdir -p ~/keys/$CI_JOB_ID
    - echo $SERV_KEY > ~/keys/$CI_JOB_ID/web-coaching-server.pem
    - chmod 600 ~/keys/$CI_JOB_ID/web-coaching-server.pem
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SERV_KEY")
  script:
    - ssh -tt -i ~/keys/$CI_JOB_ID/web-coaching-server.pem -o 'StrictHostKeyChecking=no' "$SERV_USER"@"$SERV_IP" "cd /var/www/web-coaching-yuk-fe && ./deploy.sh"
  after_script:
    - rm -rf ~/keys/$CI_JOB_ID
